[build]
  publish = "exampleSite/public"
  command = "hugo --gc --minify --source exampleSite --themesDir ../../ -t repo --baseURL $HUGO_BASE_URL"

[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASE_URL = "https://awesome-identity.netlify.com"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --source exampleSite --themesDir ../../ -t repo --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify --source exampleSite --themesDir ../../ -t repo --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
