theme = "awesome-identity"
baseURL = "https://example.com"
title = "Awesome Identity for Hugo"


## HTTP meta tags & OpenGraph Configurations
[params.meta]
  description = "Awesome Identity is a single-page Hugo theme to introduce yourself."
  keywords = "profile, about me, identity, hugo, theme"
  images = ["/images/portrait-default.png"]


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "John"
  lastname = "Smith"
  title = "VP of Engineering / Godfather"
  bio = """John Smith brings over 40 years experience leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et lacinia metus. Aliquam venenatis, orci ornare mollis congue, mi arcu lobortis tellus, id pulvinar ex ante eu mauris.

  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
  """


## Contacts Configurations
[params.contacts]
  email = "john.smith@example.com"
  github = "john.smith"
  gitlab = "john.smith"
  twitter = "john.smith"
  linkedin = "john.smith"
  instagram = "john.smith"
  stackoverflow = "7919458"
  medium = "john.smith"
  devto = "john.smith"


## Actions Configurations
[[params.actions]]
  name = "Resume"
  url = "https://example.com/resume.pdf"

[[params.actions]]
  name = "Blog"
  url = "https://blog.example.com"

[[params.actions]]
  name = "Portfolio"
  url = "https://example.com/portfolio"


## Footer Configurations
[params.footer]
  copyright = "© 2019-2026 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
