theme = "awesome-identity"
baseURL = "https://example.com"
title = "Awesome Identity for Hugo"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "John"
  lastname = "Smith"
  title = "VP of Engineering / Godfather"
  bio = """John Smith brings over 40 years experience leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et lacinia metus. Aliquam venenatis, orci ornare mollis congue, mi arcu lobortis tellus, id pulvinar ex ante eu mauris.

  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
  """


## Footer Configurations
[params.footer]
  copyright = "© 2019-2020 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
